name: worth_to_note
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  equatable:
  json_annotation:
  flutter_bloc:
  bloc:
  get_it:
  dartz:
  isar:
  isar_flutter_libs:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  isar_generator:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
